set scrolloff=0
if has('mac')
  set macligatures
  set macthinstrokes
endif
set guifont=VictorMono-Regular:h11,SourceCodePro-Regular:h12,Menlo-Regular:h12

function ChangeFontSize(delta) abort
  let l:repl = printf('\=eval(submatch(0)+%d)', a:delta)
  let &guifont = substitute(&guifont, '\d\+', l:repl, '')
endfunction
nnoremap <D-+> :call ChangeFontSize(1)<CR>
nnoremap <D--> :call ChangeFontSize(-1)<CR>
