#! /usr/bin/env bash
# Update the file `Brewfile` pre-commit to include any changes

set -euo pipefail

dir="$( cd "$( dirname "${BASH_SOURCE[0]}")" && pwd )"
BREWFILE="$PWD/brew/Brewfile"

update_brewfile() {
  brew bundle dump --force --file="$BREWFILE"
  git add "$BREWFILE"
}

update_brewfile
