#!/bin/sh

xrdb -merge ~/.Xresources
# TODO: do I also need this in i3 config? I put it there first, but it seemed to
# maybe not be permanent?
setxkbmap -option compose:caps

if ! pgrep -u benknoble picom
then picom -b
fi

exec dbus-launch --exit-with-session i3
