#! /usr/bin/env zsh

gj () {
  eval git jump $(history -1 | sed -E 's/[[:space:]]*[[:digit:]]+[[:space:]]*//' \
    | sed -E -e 's/(^git)|(^g)//' \
    -e 's/^[[:space:]]*//' \
    -e 's/^(d|diff)/diff/' \
    -e 's/^merc/merge/')
}

gj "$@"
