#! /usr/bin/env zsh

markdownify () {
  # reads from stdin
  command=(
    gh api
    --method POST
    -H 'Accept: application/vnd.github+json'
    -H 'Content-Type: text/plain'
    --input -
    /markdown/raw
  )
  "${command[@]}"
}

markdownify "$@"
