#! /usr/bin/env zsh

markdownify () {
  # reads from stdin
  command=(
    curl
    --silent
    https://api.github.com/markdown/raw
    -X "POST"
    -H "Content-Type: text/x-markdown"
    --data-binary @-
  )
  "${command[@]}"
}

markdownify "$@"
