#! /usr/bin/env zsh

ports () {
  if (($# == 0)) ; then
    {
      echo 'usage: ports port...'
      echo
      echo 'describe services on port...'
    } >&2
  else
    lsof "-i :${^@}"
  fi
}

ports "$@"
