#! /usr/bin/env bash
# Update the file `docs/tree.md` pre-commit to include any changes

set -euo pipefail

dir="$( cd "$( dirname "${BASH_SOURCE[0]}")" && pwd )"

tree_report() {
  echo '```'
  tree -L 3 --noreport
  echo '```'
}

update_tree() {
  tree_report >| docs/tree.md
  git add docs/tree.md
}

update_tree
