#! /usr/bin/env bash
# Update the file `Brewfile` pre-commit to include any changes

set -euo pipefail

dir="$( cd "$( dirname "${BASH_SOURCE[0]}")" && pwd )"

update_brewfile() {
  brew bundle dump --force
  git add Brewfile
}

update_brewfile
