#! /usr/bin/env bash
# a library of common functions for dotfiles scripts

# display a message to the user
# I can quickly tune the behavior of message display by tweaking the function
display_message() {
  printf '%s\n' "$1"
}

input_matches_yY() {
  [[ "$1" =~ ^(y|Y) ]]
}
