#! /usr/bin/env bash
# display weekly statistics about a git repo

set -euo pipefail

dir="$( cd "$( dirname "${BASH_SOURCE[0]}")" && pwd )"

# set up some common variables
USAGE='[-h]
Display a weekly summary of repo'
SUBDIRECTORY_OK=true

# source git-sh-setup for some helpers
set +u
source "$(git --exec-path)"/git-sh-setup
set -u

weekly_git_log() {
  git log --color=never --since=1.week --oneline
}

weekly_git_stats() {
  tail -n 1 <( weekly_git_log ) \
    | awk '{ print $1 }' \
    | xargs git diff --shortstat
}

features_merged() {
  {
    weekly_git_log | grep -E "Merge (pull|branch) "
  } || echo "None"
}

count_features() {
  if [[ "$1" == "None" ]]; then
    echo 0
  else
      sed '/^\s*$/d' <<<"$1" \
      | wc -l \
      | awk '{ print $1 }'
  fi
}

display_weekly_stats() {
  echo "Stats ($1 - Today)"
  echo "---------------------"
  echo "${2:-No stats available}"
  echo
  echo "Features ($3)"
  echo "-------------"
  echo "$4"
}

weekly() {
  local last_week
  last_week=$(date -v-7d +%m/%d)
  local stats
  stats="$(weekly_git_stats)"
  local features
  features="$(features_merged)"
  local features_count
  features_count="$(count_features "$features")"
  display_weekly_stats "$last_week" "$stats" "$features_count" "$features"
}

if [[ $# -gt 0 ]]; then
  usage
else
  weekly
fi
