#! /usr/bin/env bash

# set up some common variables
USAGE='[-h]
Display a weekly summary of repo'
SUBDIRECTORY_OK=true

# source git-sh-setup for some helpers
source "$(git --exec-path)"/git-sh-setup

weekly_summary() {
  LAST_WEEK=$(date -v-7d +%m/%d)
  STATS=$(
    git log --color=never --since=1.week --oneline |
    tail -n 1                                      |
    awk '{ print $1 }'                             |
    xargs git diff --shortstat
  )
  FEATURES=$(
    git log --since=1.week --oneline |
    grep -E "Merge (pull|branch) "
  )
  FEATURES_COUNT=$(
    echo "$FEATURES" |
    sed '/^\s*$/d'   |
    wc -l            |
    awk '{ print $1 }'
  )
  echo "Stats ($LAST_WEEK - Today)"
  echo "---------------------"
  echo "$STATS"
  echo
  echo "Features ($FEATURES_COUNT)"
  echo "-------------"
  echo "$FEATURES"
}

if [[ $# -gt 0 ]]; then
  usage
else
  weekly_summary
fi
