#! /usr/bin/env bash
#:  * `superclean`:
#:    Cleans up the cache and outdated version downloads, calling `cleanup -s`
#:
#:    Also calls `brew cask cleanup`
#:
#:    See `brew help cleanup` for more information

brew cleanup -s
brew cask cleanup
