name: CI
on: [push]

jobs:
  install:
    name: Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-16.04, ubuntu-18.04, macos-latest]

    steps:
      - uses: actions/checkout@v1
        with:
          submodules: true
      - if: matrix.os != 'macos-latest'
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.6.x
      - run: |
          test -d ~/.config || mkdir ~/.config
          test -d ~/.config/swi-prolog || mkdir ~/.config/swi-prolog
          test -d ~/.ssh || mkdir ~/.ssh
          ./dotfiles.plink
          make install
