name: CI
on: [push]

jobs:
  install:
    name: Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-16.04, ubuntu-18.04, macos-latest]

    steps:
      - run: |
          set +e
          command -v ruby
          command -v ruby2.3.7
          command -v ruby2.4.6
          command -v ruby2.5.5
          command -v ruby2.6.2
          echo $PATH
      - uses: actions/checkout@v1
        with:
          submodules: true
      - run: |
          ./dotfiles.plink
          make install
