name: CI
on: [push]

jobs:
  install:
    name: Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    steps:
      - uses: actions/checkout@v1
        with:
          submodules: true
      - if: matrix.os != 'macos-latest'
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.6.x
      - run: |
          ./dotfiles.plink
          make install
          eval "$(brew shellenv)"
          ./links/bin/compile-vim
